/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SAN_H_RPCGEN
#define _SAN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct envia {
	char nombre[100];
};
typedef struct envia envia;

struct retorno {
	char direccion[100];
};
typedef struct retorno retorno;

#define SAN_PROGRAMA 0x20000001
#define VERSION_SAN_PROGRAMA 1

#if defined(__STDC__) || defined(__cplusplus)
#define san 1
extern  struct retorno * san_1(struct envia *, CLIENT *);
extern  struct retorno * san_1_svc(struct envia *, struct svc_req *);
extern int san_programa_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define san 1
extern  struct retorno * san_1();
extern  struct retorno * san_1_svc();
extern int san_programa_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_envia (XDR *, envia*);
extern  bool_t xdr_retorno (XDR *, retorno*);

#else /* K&R C */
extern bool_t xdr_envia ();
extern bool_t xdr_retorno ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SAN_H_RPCGEN */
