/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "san.h"

struct retorno *
san_1_svc(struct envia *argp, struct svc_req *rqstp)
{
	static struct retorno  result;

	/*
	 * insert server code here
	 */

	return &result;
}
