/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IPS_H_RPCGEN
#define _IPS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct envia {
	char dominio[100];
};
typedef struct envia envia;

struct retorno {
	char retips[100];
};
typedef struct retorno retorno;

#define IPS_PROGRAMA 0x20000001
#define VERSION_IPS_PROGRAMA 1

#if defined(__STDC__) || defined(__cplusplus)
#define ips 1
extern  struct retorno * ips_1(struct envia *, CLIENT *);
extern  struct retorno * ips_1_svc(struct envia *, struct svc_req *);
extern int ips_programa_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ips 1
extern  struct retorno * ips_1();
extern  struct retorno * ips_1_svc();
extern int ips_programa_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_envia (XDR *, envia*);
extern  bool_t xdr_retorno (XDR *, retorno*);

#else /* K&R C */
extern bool_t xdr_envia ();
extern bool_t xdr_retorno ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IPS_H_RPCGEN */
