/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ips.h"
#include <netdb.h>
#include <string.h>
#include <arpa/inet.h>

void funcionip(char * ,char []);

struct retorno *
ips_1_svc(struct envia *argp, struct svc_req *rqstp)
{
	static struct retorno  result;




	memset(result.retips,0,100);  //agregado
	funcionip(argp->dominio,result.retips);  //agregado





	return &result;
}

// FUNCION AGREGADA
void funcionip(char * dominio, char TodasLasIp[])
{
    struct in_addr **addr_list;
    struct hostent *he = gethostbyname(dominio);

    if (he)
      { 
        int i;
        puts(he->h_name);
        printf("Servidor Dice Nombre del Host : %s\n", he->h_name);
        printf("Servidor Dice Direcciones IP  ");
        addr_list = (struct in_addr **)he->h_addr_list;
        for(i = 0; addr_list[i] != NULL; i++)
           {
            printf("%s \n", inet_ntoa(*addr_list[i]));
            strcat(TodasLasIp,(char*) inet_ntoa(*addr_list[i]));
            strcat(TodasLasIp,"\n");
          }
        printf("\n");
      }
    else
     {       
        printf("Servidor dice error gethostbyname\n");
		strcat(TodasLasIp,"error gethostbyname\n");
	}   
}
