/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SNA_H_RPCGEN
#define _SNA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct envia {
	char nombre[100];
};
typedef struct envia envia;

struct retornoDireccion {
	int disponible;
	char direccion[15];
};
typedef struct retornoDireccion retornoDireccion;

#define SNA_SOLICITAR_DIRECCION_PROGRAMA 0x20000001
#define VERSION_SNA_SOLICITAR_PROGRAMA 1

#if defined(__STDC__) || defined(__cplusplus)
#define sna_solicitar 1
extern  struct retornoDireccion * sna_solicitar_1(struct envia *, CLIENT *);
extern  struct retornoDireccion * sna_solicitar_1_svc(struct envia *, struct svc_req *);
extern int sna_solicitar_direccion_programa_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sna_solicitar 1
extern  struct retornoDireccion * sna_solicitar_1();
extern  struct retornoDireccion * sna_solicitar_1_svc();
extern int sna_solicitar_direccion_programa_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_envia (XDR *, envia*);
extern  bool_t xdr_retornoDireccion (XDR *, retornoDireccion*);

#else /* K&R C */
extern bool_t xdr_envia ();
extern bool_t xdr_retornoDireccion ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SNA_H_RPCGEN */
