/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sna.h"


void
sna_solicitar_direccion_programa_1(char *host, char *nombre, char *direccion, int *disponible)
{
	CLIENT *clnt;
	struct retornoDireccion  *result_1;
	struct envia  sna_solicitar_1_arg = {0}; 

#ifndef	DEBUG
	clnt = clnt_create (host, SNA_SOLICITAR_DIRECCION_PROGRAMA, VERSION_SNA_SOLICITAR_PROGRAMA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	//agregar argumento a funcion
	strcpy(sna_solicitar_1_arg.nombre, nombre);

	result_1 = sna_solicitar_1(&sna_solicitar_1_arg, clnt);
	if (result_1 == (struct retornoDireccion *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */

	printf("test del cliente\n");

	//result_1 tiene disponible y nombre
	*disponible = result_1->disponible;
	strcpy(direccion, result_1->direccion);

	printf("disponible %d | direccion %s\n", *disponible, direccion);

	if (*disponible == 1) {
		printf("archivo disponible en direccion %s\n", direccion);
	} else {
		printf("archivo no disponible\n");
	}
}


int
almacenarDireccionArchivo(char* nombre, char* direccion) 
{
	FILE *fp = fopen("archivos.txt", "a");
    if (fp == NULL) {
        printf("error reading file\n");
        return -1;
	}

	fprintf(fp, "%s,%s\n", nombre, direccion);
	fclose(fp);

	return 0;
}


int
main (int argc, char *argv[])
{
	char *host; 
	char direccion[256] = {0}; 
	int disponible = 0;      

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sna_solicitar_direccion_programa_1 (host, argv[2], direccion, &disponible); 
	
	if (!disponible) {
		exit(0); //archivo no disponible
	}

	//busqueda de archivo en otro rpc
	//guardar en tabla de archivos en su posesión tipo tabla arp pero que todos los que esten ahi esten bloqueados para el

	//almacenar en tabla de archivos controlados
	if (0 == almacenarDireccionArchivo(argv[2], direccion)) {
		printf("\narchivo almacenado en archivosControlados\n");
	}

	exit (0);
}
