/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sna.h"

bool_t
xdr_envia (XDR *xdrs, envia *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nombre, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_retornoDireccion (XDR *xdrs, retornoDireccion *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->disponible))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->direccion, 15,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
