/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "sna.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct retornoDireccion *
sna_solicitar_1(struct envia *argp, CLIENT *clnt)
{
	static struct retornoDireccion clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, sna_solicitar,
		(xdrproc_t) xdr_envia, (caddr_t) argp,
		(xdrproc_t) xdr_retornoDireccion, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
